### PR TITLE
Update everything 🎉

### PR DESCRIPTION
**Pull request by anehx**
* Drop bower dependency
* Use AMD module of autolinker
* Set some ESlint rules
* Use yarn
* Add unit tests
* Add coverage testing
* Replace ember-cli-qunit with ember-cli-mocha :heart:

### CODE REVIEW

**Comment by czosel** [comment]
Awesome work! :100: 

One question: Should we use prettier without `no-semi`? It's closer to the default styling of ember code, isn't it?

**Comment by anehx** [comment]
@czosel Yeah it sure is closer to the default ember styling, but not closer to our company guidelines.. I actually don't even care as long as we keep it consistent over all our ember addons.

Do you think we should use semicolons in all our addons to satisfy the ember default?

**Comment by czosel** [comment]
I'd suggest
* ember default for library-style addons (validated-form, autolinker) (pretty much all addons i guess)
* company defaults for apps (timed, adsycc)

**Comment by anehx** [comment]
Works for me!

**Comment by anehx** [comment]
Done!

**Review by czosel — APPROVED** [review]

**Pull request merged**
